# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\EntityListener\PurchaseEntityListener:
        tags:
            - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Purchase'}
            # - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Conference'}

    App\EntityListener\SettingsEntityListener:
        tags:
            - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Settings'}
            # - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Conference'}

    App\EntityListener\CustomerEntityListener:
        tags:
            - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Customer'}
            # - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Conference'}

    admin.product:
        class: App\Admin\ProductAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Product, controller: ~, manager_type: orm, group: admin, label: Product }

    admin.customer:
        class: App\Admin\CustomerAdmin
        calls:
            - setEntityManager: ['@doctrine.orm.default_entity_manager']
        tags:
            - { name: sonata.admin, model_class: App\Entity\Customer, controller: ~, manager_type: orm, group: admin, label: Customer }

    admin.purchase:
        class: App\Admin\PurchaseAdmin
        # calls:
        #     - setSettingsRepository: ['@settingsRepository']
        tags:
            - { name: sonata.admin, model_class: App\Entity\Purchase, controller: ~, manager_type: orm, group: admin, label: Purchase }

    admin.bill:
        class: App\Admin\BillAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Bill, controller: ~, manager_type: orm, group: admin, label: Bill }

    admin.field:
        class: App\Admin\FieldAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Field, controller: ~, manager_type: orm, group: admin, label: Field }

    admin.settings:
        class: App\Admin\SettingsAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Settings, controller: ~, manager_type: orm, group: admin, label: Settings }
